# Generated by Django 4.1.2 on 2022-10-29 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modelapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Tag", new_name="Symp",),
    ]
