# Generated by Django 4.0.2 on 2022-11-19 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0002_rename_tag_symp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDesc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField()),
            ],
        ),
    ]
