# Generated by Django 4.0.2 on 2022-11-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
