# Generated by Django 4.0.2 on 2022-11-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='queryToDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listosymp', models.TextField()),
                ('predDiseases', models.TextField()),
                ('note', models.TextField()),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
