# Generated by Django 4.0.2 on 2022-11-21 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0008_querytodoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytodoc',
            name='listosymp',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='querytodoc',
            name='predDiseases',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
