# Generated by Django 4.1.2 on 2022-11-21 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0011_querytodoc_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querytodoc',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
