# Generated by Django 4.1.2 on 2022-12-17 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0014_querytodoc_docnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='querytodoc',
            name='probsolve',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
